{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-shogun
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - SHOGUN
    - bowtie2
    - cytoolz

test:
  imports:
    - q2_shogun
    - qiime2.plugins.shogun

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
